# Generated by Django 5.0.4 on 2024-06-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
